### ISSUE TITLE
Production Report Forms have extra space / gap between them.

### ISSUE THREAD

**Issue by ksdhir** [Haidoe/arc#109]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
The Rolls form seem to have less content and therefore there is some extra space between it and the next component.

**Steps to reproduce: ❗️**
1. Go to '[Home Page'](https://arc-app.ca/home)
2. Click on 'Any existing production'
3. Scroll and see the gap between 'forms'

**Screenshots or Video**
![Screenshot 2023-07-16 at 9 17 00 PM](https://github.com/Haidoe/arc/assets/44022086/c3d125f9-bbfe-491f-9f3d-becd47ceb5c9)

**Expected behavior:  ❗️**
The gap or space should be consistent between the forms.

**Actual behavior:  ❗️**
A clear and concise description of what actually happened.

**Possible Solution:**
Perhaps the forms could be given a 'min-height' so they look as expected. Height with Scrollbar could also be an option but the content of the first three forms will always remain the same i.e the height will never change.

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by ksdhir** [comment]
This was fixed under commit https://github.com/Haidoe/arc/commit/bd677920eeb33ba81435f486edc15ddcf90755cd
Please verify @StephanyJade

**Comment by StephanyJade** [comment]
@ksdhir 
cc: @jbsinluenam @Haidoe 

I'm testing TODAY WED 19 and the issue remains. URL: https://arc-kaos.vercel.app/production/64b2eef57bc969ee0122a5c4/report
<img width="1664" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/0c7a4664-bd5b-4461-b392-8a986e9a7cf7">

Reassigning Haids and JB.

Thank you.

**Comment by Haidoe** [comment]
HI @StephanyJade ,

Please use this url for testing: https://arc-git-dev-haidoe.vercel.app/
